### ISSUE TITLE
ボタンを連打するとページが空白になる

### ISSUE THREAD

**Issue by oka4shi** [SenraiJP/SenraiJP.github.io#3]
以下の動画のように、ナビゲーションのボタンを押す間隔が短いとページが真っ白になります。
※Discordでは既に報告済み
https://youtu.be/ibh0Bpffke8

**Comment by saladbowl77** [comment]
修正版出します

**Comment by oka4shi** [comment]
fb72d5babdd87ae4cfc01a626fbf1973726a4f09 で修正されました

**Comment by saladbowl77** [comment]
修正しました。
しかし他のバグも出そうなので全体的な改変が必要になりそうです。

具体的な修正について
cssの読み込む場所を間違えていたのと、変数等の変更を行いました。
var check = 0;に数字を入れることで現在の状態を判別できるようにしました。
0 = 何も動いていない通常状態
1 = 何か動いている状態
1になっている時は動かすことができない
`
if (check == 0) {
 -----処理-----
}
`
このように書くことで現在動作中かどうかを判断します。

**Comment by oka4shi** [comment]
6bb6c69df20c2f550902f9e3059c494ac9a63a51
で完全に修正されました。

 また、 #6 で
let isAnimatingNow = Boolean(false);に真偽値を入れることで現在の状態を判別できるようにしました。
false = 何も動いていない通常状態
true = 何か動いている状態
trueになっている時は動かすことができない
`
if (isAnimatingNow) { -----処理----- }
`
このように書くことで現在動作中かどうかを判断します。
